name: Dokkoi
main: org.meyason.dokkoi.Dokkoi
version: '1.0-SNAPSHOT'
main: org.meyason.dokkoi.Dokkoi
api-version: '1.21'

commands:
  matching:
    description: マッチングを開始します．
    usage: /matching
    default: op
  reset:
    description: マッチングデータをリセットします．
    usage: /reset
    default: op
  goalfix:
    description: 職業を固定します．None指定で解除します．
    usage: /goalfix <player> <job>
    default: op