name: Dokkoi
main: org.meyason.dokkoi.Dokkoi
version: '1.0-SNAPSHOT'
api-version: '1.21'
depend: [ProtocolLib]

commands:
  matching:
    description: マッチングを開始します．
    usage: /matching
    default: op
  end:
    description: 試合を強制終了します．
    usage: /end
    default: op
  spawnentity:
    description: エンティティをスポーンさせます．
    usage: /spawnentity <entity id>
    default: op
  getitem:
    description: アイテムを取得します．
    usage: /getitem <item id> <amount>
    default: op
  addLP:
    description: LPを追加します．
    usage: /addLP <player> <amount>
    default: op
  edit:
    description: ワールドを編集します．
    usage: /edit
    default: op
  itemInfo:
    description: 手に持ったアイテムの情報を表示します．
    usage: /info