name: Dokkoi
main: org.meyason.dokkoi.Dokkoi
version: '1.0-SNAPSHOT'
api-version: '1.21'

commands:
  matching:
    description: マッチングを開始します．
    usage: /matching
    default: op
  end:
    description: 試合を強制終了します．
    usage: /end
    default: op
  goalfix:
    description: 職業を固定します．None指定で解除します．
    usage: /goalfix <player> <job>
    default: op
  spawnentity:
    description: エンティティをスポーンさせます．
    usage: /spawnentity <entity id>
    default: op