CREATE DATABASE IF NOT EXISTS DOKKOI CHARACTER SET utf8 COLLATE utf8_general_ci;

use Dokkoi;

CREATE TABLE IF NOT EXISTS users(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);